### ISSUE TITLE
Steps for Docker Compose

### ISSUE THREAD

**Issue by Poldi1977** [Worklenz/worklenz#27]
Hello

I came across this project yesterday and think it's really exciting! I would like to install it on my server on a trial basis. I am missing the installation steps for Docker Compose. Could someone briefly describe the steps required to do this?

Have a nice weekend
Tim

**Comment by kalinga777** [comment]
Hi Tim,

We have released a new version few days back. The documentation is available and we will improve the documentation as soon as possible

**Comment by DhavalThkkar** [comment]
@kalinga777 It doesn't work. Need steps to get it up and running. I'm fed up of trying different things but still can't get it to work. Any help is appreciated

**Comment by kalinga777** [comment]
@DhavalThkkar  Thank you for letting us know.  Will it be possible to send the error logs if you have? @chamikaJ

**Comment by aaron13223** [comment]
Here's the compose with generic details:

```
  worklenz:
    build:
      context: ./worklenz/build/worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz
    ports:
      - 4200:4200
    depends_on:
      worklenz-backend:
        condition: service_started
    restart: always

  worklenz-backend:
    build:
      context: ./worklenz/build/worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz-backend
    ports:
      - 3000:3000
    depends_on:
      worklenz-db:
        condition: service_healthy
    environment:
      DB_HOST: worklenz-db
      DB_NAME: worklenz_db
      DB_PASSWORD: worklenz
      DB_USER: worklenz_backend
    restart: always

  worklenz-db:
    image: postgres:15
    container_name: worklenz-db
    environment:
      POSTGRES_DB: worklenz_db
      POSTGRES_PASSWORD: worklenz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d worklenz_db -U worklenz_client"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./worklenz/db:/var/lib/postgresql/data
      - ./worklenz/backend-db/:/docker-entrypoint-initdb.d
  ```

You will have to clone the repo and change the build directory accordingly alongside copying worklenz-backend/database directory to the correct folder (/worklenz/backend-db/ in this case)

I also had an issue with the "6_user-permission.sql" so I had to edit the CREATE ROLE command: (pretty sure this is very insecure)

```
CREATE ROLE worklenz_client WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
```

The error showing up in postgres was that the role worklenz_client did not have login permissions.

Also still haven't figured out how to set up an account on this things locally lmao.

**Comment by aaron13223** [comment]
> Hello
> 
> I came across this project yesterday and think it's really exciting! I would like to install it on my server on a trial basis. I am missing the installation steps for Docker Compose. Could someone briefly describe the steps required to do this?
> 
> Have a nice weekend Tim

Here's an example docker compose file:

```
worklenz:
    build:
      context: ./worklenz/build/worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz
    ports:
      - 4200:4200
    depends_on:
      backend:
        condition: service_started
    restart: always
    networks:
      - worklenz

  backend:
    build:
      context: ./worklenz/build/worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz-backend
    ports:
      - 3000:3000
    depends_on:
      worklenz-db:
        condition: service_healthy
    environment:
      - DB_HOST=worklenz-db
      - DB_NAME=worklenz_db
      - DB_PASSWORD=worklenz
      - DB_USER=worklenz_backend
      #- ANGULAR_DIST_DIR: test
      #- ANGULAR_SRC_DIR: test
      #- AWS_REGION: test
      #- BACKEND_PUBLIC_DIR: test
      #- BACKEND_VIEWS_DIR: test
      #- COMMIT_BUILD_IMMEDIATELY: test
      #- COOKIE_SECRET: test
      #- GOOGLE_CALLBACK_URL: test
      - GOOGLE_CLIENT_ID=test
      - GOOGLE_CLIENT_SECRET=test
      #- HOSTNAME="192.168.0.139"
      - PORT=3000
      - SESSION_NAME=test
      - SESSION_SECRET=test
      #- SLACK_WEBHOOK: test
      #- SOCKET_IO_CORS: test
      - SOURCE_EMAIL="aaron13223@gmail.com"
      #- USE_PG_NATIVE: test
      #- BUCKET: test
      #- REGION: test
      - S3_URL=test
      - S3_ACCESS_KEY_ID=test
      - S3_SECRET_ACCESS_KEY=test
    restart: always
    networks:
      - worklenz

  worklenz-db:
    image: postgres:15
    container_name: worklenz-db
    environment:
      POSTGRES_DB: worklenz_db
      POSTGRES_PASSWORD: worklenz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d worklenz_db -U worklenz_client"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /xyz/worklenz/db:/var/lib/postgresql/data
      - /xyz/worklenz/backend-db/:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - worklenz
```

Make sure to edit the volumes for the database and add a network in the compose file like so:

```
networks:
  worklenz:
```

You also have to clone the repo and copy the folder worklenz-backend/database to /xyz/worklenz/backend-db/ (Refere to the compose file above)

I did have one issue so I had to edit the "6_user-permission.sql" file. The postgres instance was giving out errors that the role does not have login permissions. So I edited the CREATE ROLE line to this (prolly very insecure and can get rid of some permissions):

```
CREATE ROLE worklenz_client WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
```

After  a lot of tinkering, I was able to get it up and running this way :p (at least as a test)

**Comment by twinmoonsllc** [comment]
I've tried to get this working with no luck. I'm sorry to say, the Docker documentation for this is pretty horrible. I keep getting this error in the log:

2025-03-14 00:42:42.230 UTC [74] FATAL:  role "worklenz" does not exist
